from pathlib import Path

def replace(path, old, new):
    p=Path(path); s=p.read_text()
    if old not in s: raise SystemExit(f'missing pattern in {path}: {old[:80]!r}')
    p.write_text(s.replace(old,new,1))

replace('src/Components/MyBookings.jsx','  AlertTriangle,\n} from "lucide-react";','  AlertTriangle,\n  Radio,\n} from "lucide-react";')
replace('src/Components/MyBookings.jsx','import { useI18n } from "../context/I18nContext.jsx";\n','import { useI18n } from "../context/I18nContext.jsx";\nimport LiveWorkerTracking from "./shared/LiveWorkerTracking.jsx";\n')
replace('src/Components/MyBookings.jsx','  assigned: {\n    icon: UserCheck,\n    color: "text-purple-600",\n    bg: "bg-purple-50",\n    border: "border-purple-200",\n    label: "Worker Assigned",\n    priority: 0,\n  },','  assigned: {\n    icon: UserCheck,\n    color: "text-purple-600",\n    bg: "bg-purple-50",\n    border: "border-purple-200",\n    label: "Worker Assigned",\n    priority: 0,\n  },\n  "on-the-way": {\n    icon: Radio,\n    color: "text-orange-600",\n    bg: "bg-orange-50",\n    border: "border-orange-200",\n    label: "On The Way",\n    priority: 0,\n  },')
replace('src/Components/MyBookings.jsx','  const [statusNotice, setStatusNotice] = useState("");\n','  const [statusNotice, setStatusNotice] = useState("");\n  const [trackingBookingId, setTrackingBookingId] = useState(null);\n')
replace('src/Components/MyBookings.jsx','["assigned", "in-progress"].includes(b.status) &&','["assigned", "on-the-way", "in-progress"].includes(b.status) &&')
replace('src/Components/MyBookings.jsx','''                          {b.worker && (\n                            <div className="text-right">\n                              <p className="text-xs text-slate-500 font-medium">\n                                Worker Assigned\n                              </p>\n                              <p className="text-sm font-bold text-slate-900">\n                                {b.worker.fullName}\n                              </p>\n                            </div>\n                          )}\n                          <button className="text-slate-400 hover:text-slate-600 transition-colors p-1">''','''                          {b.worker && (\n                            <div className="text-right">\n                              <p className="text-xs text-slate-500 font-medium">\n                                Worker Assigned\n                              </p>\n                              <p className="text-sm font-bold text-slate-900">\n                                {b.worker.fullName}\n                              </p>\n                            </div>\n                          )}\n                          {b.worker && ["on-the-way", "in-progress"].includes(b.status) && (\n                            <button\n                              type="button"\n                              onClick={(event) => {\n                                event.stopPropagation();\n                                setTrackingBookingId(b.id);\n                              }}\n                              className="inline-flex items-center gap-1.5 rounded-lg bg-emerald-600 px-3 py-2 text-xs font-bold text-white shadow-sm transition-colors hover:bg-emerald-700"\n                            >\n                              <Radio size={14} />\n                              Live Tracking\n                            </button>\n                          )}\n                          <button className="text-slate-400 hover:text-slate-600 transition-colors p-1">''')
replace('src/Components/MyBookings.jsx','''          </div>\n        </div>\n      </div>\n    </div>\n  );\n}''','''          </div>\n          {trackingBookingId && (\n            <div className="fixed inset-0 z-[90] flex items-center justify-center px-4 py-6">\n              <button type="button" onClick={() => setTrackingBookingId(null)} className="absolute inset-0 bg-slate-950/60 backdrop-blur-sm" aria-label="Close live tracking" />\n              <div className="relative w-full max-w-2xl max-h-[90vh] overflow-y-auto rounded-2xl bg-white shadow-2xl">\n                <div className="flex items-center justify-between border-b border-slate-200 px-4 py-3">\n                  <div><p className="text-sm font-bold text-slate-900">Live Tracking</p><p className="text-xs text-slate-500">Your worker's live location</p></div>\n                  <button type="button" onClick={() => setTrackingBookingId(null)} className="rounded-lg p-2 text-slate-400 hover:bg-slate-100 hover:text-slate-700"><X size={18} /></button>\n                </div>\n                <LiveWorkerTracking bookingId={trackingBookingId} />\n              </div>\n            </div>\n          )}\n        </div>\n      </div>\n    </div>\n  );\n}''')
replace('src/App.jsx','import CustomerLiveTrackingHost from "./Components/shared/CustomerLiveTrackingHost.jsx";\n','')
replace('src/App.jsx','              <CustomerLiveTrackingHost />\n','')
replace('src/Components/shared/LiveWorkerTracking.jsx','const ACTIVE_STATUSES = new Set(["assigned", "worker-assigned", "in-progress"]);','const ACTIVE_STATUSES = new Set(["assigned", "worker-assigned", "on-the-way", "in-progress"]);')
