/** Primary trade options for worker signup (searchable dropdown). */
export const WORKER_TRADE_OPTIONS = [
  "Electrician",
  "Plumber",
  "AC / HVAC Technician",
  "Carpenter",
  "Painter",
  "Mason / Construction",
  "Welder",
  "Steel Fabricator",
  "Tile / Marble Worker",
  "POP / False Ceiling",
  "Glass & Aluminum",
  "Roofer",
  "Waterproofing",
  "Solar Panel Installer",
  "CCTV & Security Systems",
  "Generator Repair",
  "Appliance Repair",
  "Refrigerator / AC Repair",
  "Washing Machine Repair",
  "Mobile / Laptop Repair",
  "Computer / Network IT",
  "Home Cleaning",
  "Deep Cleaning / Sanitization",
  "Pest Control",
  "Gardening / Landscaping",
  "Driver / Delivery",
  "Mover / Packers",
  "Furniture Assembly",
  "Interior Designer",
  "Event Setup / Tent",
  "Catering Helper",
  "Tailor / Alterations",
  "Beauty / Salon at Home",
  "Massage / Physiotherapy",
  "Tutor / Home Teacher",
  "Babysitter / Caregiver",
  "Pet Care / Grooming",
  "Car Mechanic",
  "Bike Mechanic",
  "Car Wash / Detailing",
  "Tyre Puncture / Wheel Alignment",
  "Auto Electrician",
  "Denting & Painting",
  "Other",
];
